### PR TITLE
fixed naming for multiple GPUs in amd_gpu_; adjusted lower limit for …

### PR DESCRIPTION
**Pull request by inbaz**
…temperature to 20

### CODE REVIEW

**Comment by sumpfralle** [comment]
Thank you for your improvement proposal!

I am not sure about the sed statement: would it work with a CPU count > 9?

**Comment by sumpfralle** [comment]
@inbaz: what do you think?

**Comment by inbaz** [comment]
Uh, sorry for the late response, yes sure, it needs to be [0-9]+ to support more than 9 GPUs.

**Comment by sumpfralle** [comment]
Thank you!

**Pull request merged**
