### PR TITLE
Use an environment variable for CACHE_EXPIRY

### PR DESCRIPTION
**Pull request by ruliane**

### CODE REVIEW

**Comment by sumpfralle** [comment]
Thank you!

**Comment by sumpfralle** [comment]
Finally the CI result arrived: https://travis-ci.org/github/munin-monitoring/contrib/builds/756724561

You need to quote the `${CACHE_EXPIRY}` in order to satisfy `shellcheck`. Thanks!

**Comment by ruliane** [comment]
> Finally the CI result arrived: https://travis-ci.org/github/munin-monitoring/contrib/builds/756724561
> 
> You need to quote the `${CACHE_EXPIRY}` in order to satisfy `shellcheck`. Thanks!

Fixed.

**Comment by sumpfralle** [comment]
Thank you!

**Pull request merged**
