### PR TITLE
Fix QOS plugins

### PR DESCRIPTION
**Pull request by smith153**
Modified the QOS monitoring plugins. Seemed to be out of date or just not working.

### CODE REVIEW

**Comment by smith153** [comment]
Added some fixes to modem-nvg510 as well.

**Comment by smith153** [comment]
Fixed weather plugins dependent on the now decommissioned weather.noaa.gov interface.

**Comment by smith153** [comment]
Can this get fork get merged? These are all bug fixes.

**Comment by sumpfralle** [comment]
Thank you!

**Pull request merged**
