### PR TITLE
Nextcloud serverinfo

### PR DESCRIPTION
**Pull request by shtrom**
Here's a work in progress to get data out of the Nextcloud (and maybe ownCloud) serverinfo endpoint. Most of the useful data is extracted, but the rendering is still somewhat dodgy. I'm putting this PR out for comments and suggestions.

This is a multigraph plugin, but due to the scale of the various metrics, I ended up using log scale for the Y axis to get some sort of legibility out of it
screen shot 2018-09-10 at 13 47 34

Then you can expand it, and see more details</summary>
screen shot 2018-09-10 at 13 47 48
screen shot 2018-09-10 at 13 51 09

I also included some textual information such as versions, but that could probably be better shown, or at least not added to a series that is always `n/a`

screen shot 2018-09-10 at 13 56 18
screen shot 2018-09-10 at 13 53 54

Anyway, at this stage, it's ugly but it works. Comments and suggestions for improvement are most welcome.

### CODE REVIEW

**Comment by Sephtex** [comment]
I might be interested in using this, so it would be nice if it could be merged to master.
The only improvements which might be interesting is to have 2(4) other extra graphs:
- a graph which lists all the users, their usages with their limits (1 amount of files, 1 amount in disk space)
- A module where you can create a symlink of the module for each user (also 1 for the amount of files, 1 for the amount in disk space)

**Comment by shtrom** [comment]
On Sun 03 Feb 2019 at 10:31:58 -0800, Sephtex wrote:
>I might be interested in using this, so it would be nice if it could be merged to master.
>The only improvements which might be interesting is to have 2(4) other extra graphs:
>- a graph which lists all the users, their usages with their limits (1 amount of files, 1 amount in disk space)
>- A module where you can create a symlink of the module for each user (also 1 for the amount of files, 1 for the amount in disk space)

Hum, I don't remember the per-user info being made available from the 
serverinfo when I last touched this... Has it been added recently, or 
did I just miss it?

If it is indeed in the serverinfo, it is easy to add.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by Sephtex** [comment]
> On Sun 03 Feb 2019 at 10:31:58 -0800, Sephtex wrote: I might be interested in using this, so it would be nice if it could be merged to master. The only improvements which might be interesting is to have 2(4) other extra graphs: - a graph which lists all the users, their usages with their limits (1 amount of files, 1 amount in disk space) - A module where you can create a symlink of the module for each user (also 1 for the amount of files, 1 for the amount in disk space)
> Hum, I don't remember the per-user info being made available from the serverinfo when I last touched this... Has it been added recently, or did I just miss it? If it is indeed in the serverinfo, it is easy to add.
> […](#)
> -- Olivier Mehani <shtrom@ssji.net> PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE F5F9 F012 A6E2 98C6 6655 Confidentiality cannot be guaranteed on emails sent or received unencrypted.

Not that I know of. I don't know the serverinfo as I only started to play recently with nextcloud (install wise way). (didn't really used it yet)
If it's not there, the information could be extracted from the database if a connectionstring might be provided through the module configuration. Although that might not be the best way as not everyone will use an external database, and the table structure might change.
I could check the nextcloud issues to request this as a new feature, if it isn't yet there.

**Comment by sumpfralle** [comment]
@shtrom: how do you see the state of this plugin? Is it still *work in progress*?

**Comment by shtrom** [comment]
This one is still very much a work in progress. It works well, but I don't like the presentation

**Comment by brknkfr** [comment]
Just in case, I started another simple multigraph nextcloud plugin, see #1056

**Comment by shtrom** [comment]
Ugh, I didn't know there was a JSON output 🤦‍♂ That certainly makes things easier...

**Comment by sumpfralle** [comment]
@shtrom: I just merged the plugin from #1056. Do you want to keep this proposal open in order to merge potentially missing details into that plugin? Or what do you think?

**Comment by shtrom** [comment]
Nah, if the other plugin works, let's stick with that one.

**Pull request closed without merging**
