### PR TITLE
spelling fixes

### PR DESCRIPTION
**Pull request by ka7**
patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.

### CODE REVIEW

**Comment by sumpfralle** [comment]
Nice - that looks good!

Could you please rebase your branch? There seem to be conflicts.

**Comment by ka7** [comment]
sorry for the mess. still have to learn some aspects of git..

**Comment by sumpfralle** [comment]
There always new things to learn :)

The result of your latest commits create the proper changeset.
... but your last commit (c96b50ef8fd260d98bfb9fbda0973689ff8a8b47) was a merge (at least I think so), thus it touched a thousand files. This does not really hurt, but it messes up the history.

Thus please pick one of the following three approaches:
A) rebase your branch via github's web interface: https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/
B) create a new fork and repeat your automatic spelling check operation (if this is not soo time consuming)
C) create a new fork and run `git merge --squash OLD_BRANCH` - this should apply all changes to your current working directory

Please ask, if you have any further questions.
Your changes are great and very welcome!

**Comment by sumpfralle** [comment]
Do you need some more hints regarding the rebase?

**Comment by ka7** [comment]
so, method (A) applied, at least guess so.. :)

**Comment by sumpfralle** [comment]
I am afraid, that this was not the right approach :(
(maybe it is the fault of github's handling - I cannot tell)

Your commit was a "merge" between your branches "features/spelling" and your "master".
(*your* "master" - which is quite a number of commits behind the "master" of this contrib repository)

Now there are three options:
A) you are interested in understanding the workings of git at this moment - then I will guide you through the process (via the commandline)
B) you create another clean patchset (either via your bot or via git: `git diff remotes/munin/master...remotes/ka7/feature/spelling`) and apply it to a new clean branch
C) I do (B) instead of you (easy to do - based on the git diff)

Which path do you choose?

**Comment by ka7** [comment]
i will close this one and re-do based on fresh bot-results.
see here: #834
could refresh the master and download the patch-file ( <this-url>.patch ), could apply to 99%.

**Pull request closed without merging**
