### PR TITLE
Pluging to monitor promises kept/not kept/repaired in cfengine 3.6

### PR DESCRIPTION
**Pull request by didier-contribs**
Nice way to see if your promises are idempotent, and if your machine is doing the right things

### CODE REVIEW

**Comment by sumpfralle** [comment]
@didier-contribs: are you still interested in these plugins? What do you think about the issues above?

**Comment by sumpfralle** [comment]
@didier-contribs: any thoughts?

**Comment by sumpfralle** [comment]
@didier-contribs: ping?

**Comment by didier-contribs** [comment]
Sorry for not being there, I'm back but I'm not interested in the plugin anymore, feel free to do what you want with it

**Pull request closed without merging**
