### PR TITLE
Fix mongo_collection_

### PR DESCRIPTION
**Pull request by jrmsgit**
Hi:

I'm just humbly providing this patch as I found that mongodb_collection_ env.mongodb_uri setting was not being loaded.

Let me know please if you have any question.

Thanks all for your work on this project.

Cheers,

Jeremías

### CODE REVIEW

**Comment by sumpfralle** [comment]
I guess, this is superseded by your more recent proposal (#1190)?

**Comment by jrmsgit** [comment]
Hi:

> I guess, this is superseded by your more recent proposal (#1190)?

Well, I tried to fix them both in separate (conflicting sorry) patches. I didn't want to mess up different type of changes in the same PR. But I'm not sure if that was a good idea...

Anyway, I wanted to fix "both"... To make the script load env.mongodb_uri as it was expected to do... And to also support the load MONGO_DB_URI as from #1190 pr.

I would apply both patches. But only applying #1190 should be "enough" I think.

Thanks!!


Jeremías

**Comment by sumpfralle** [comment]
> Well, I tried to fix them both in separate (conflicting sorry) patches. I didn't want to mess up different type of changes in the same PR. But I'm not sure if that was a good idea...

If two sets of changes depend on each (and are rather trivial), then I would consider it to be appropriate to fix both in one PR (as separate commits). It is just a matter of taste.

> [.. ]

I am not sure, I understood the rest of your comment fully :)

Thus summarizing:

* #1190 is merged now
* is there something else in this PR (#1189), that needs to be merged?

Thanks!

**Comment by jrmsgit** [comment]
Hi:

> > Well, I tried to fix them both in separate (conflicting sorry) patches. I didn't want to mess up different type of changes in the same PR. But I'm not sure if that was a good idea...
> 
> If two sets of changes depend on each (and are rather trivial), then I would consider it to be appropriate to fix both in one PR (as separate commits). It is just a matter of taste.
> 

Good, thanks for the explanation... I will keep it in mind for future patches.

> > [.. ]
> 
> I am not sure, I understood the rest of your comment fully :)

My apologies!

> 
> Thus summarizing:
> 
>     * #1190 is merged now
> 
>     * is there something else in this PR (#1189), that needs to be merged?
> 
> 
> Thanks!

Trying to be brief, the script was expected to load monbodb_uri env variable[0]. But it wasn't loaded in the ifs list[1]. So I proposed this patch to fix that. Which I think should be applied, as it fixes what I think is a bug.

  0: https://github.com/munin-monitoring/contrib/blob/master/plugins/mongodb/mongo_collection_#L41
  1: https://github.com/munin-monitoring/contrib/blob/master/plugins/mongodb/mongo_collection_#L160

Then I proposed later the load of MONGO_DB_URI env var as a common setting for all the scripts. Which I think are separate issues/patches, but both apply.

So, if you agree I would apply this patch too.

Let me know please if you have any question.

Thanks for your time on this!

Cheers,


Jeremías

**Comment by sumpfralle** [comment]
> Trying to be brief, the script was expected to load monbodb_uri env variable[0]. But it wasn't loaded in the ifs list[1]. 

ah - thanks for the explanation!

Yes, in this case I would be grateful, if you could rebase your patch onto the current state of the master branch. Thank you!

**Comment by jrmsgit** [comment]
Hi:

> Yes, in this case I would be grateful, if you could rebase your patch onto the current state of the master branch. Thank you!

I think it's ready now. Sorry for all the confusion.

Thanks!!

Jeremías

**Comment by sumpfralle** [comment]
Thanks!

... but sadly, your branch is a bit more complicated, than necessary :(
(containing a commit, a merge and another commit)

Could you manage to clean this up, please?
(e.g. create a new branch based on master, cherry-pick your two real commits and squash them via rebase)

Thank you!

**Comment by jrmsgit** [comment]
Hi:

> ... but sadly, your branch is a bit more complicated, than necessary :(
> (containing a commit, a merge and another commit)
> 

My apologies! For the mess, and for the delay on replying...

> Could you manage to clean this up, please?
> (e.g. create a new branch based on master, cherry-pick your two real commits and squash them via rebase)

I just tried, but maybe I made it worst? Not sure sorry... If that didn't work I guess I could open a new PR and do it properly.

Thanks for your time!

Cheers,


Jeremías

**Comment by sumpfralle** [comment]
> I just tried, but maybe I made it worst? Not sure sorry... If that didn't work I guess I could open a new PR and do it properly.

Yes, it looks a bit worse :)

Now I just cherry-picked your commit manually - thanks!

In order to get rid of unwanted merge commits, I would recommend to start from a clean state (e.g. the `master` branch) and then simply cherry-pick your commit(s). Just for your future endeavors ...

**Pull request closed without merging**
