### PR TITLE
add postfix-policyd-spf-python plugin

### PR DESCRIPTION
**Pull request by lynix**
Very simple but useful plugin to monitor postfix-policyd-spf classification results. Written by me some time ago, but still works :)

### CODE REVIEW

**Comment by ssm** [comment]
Could you pick a license for it, please, and add it to the plugin?

Either a copyleft or permissive opensource license would be fine, but it should be explicitly stated which license to use in the plugin.

**Comment by lynix** [comment]
Sure, I'd like to go with the MIT license (although I don't care much, so if you've got a better suggestion I'm open to it). Shall I paste the entire license in the script or just state the name of the license?

I'm a bit irritated because I've seen many plugins without any license information (partially even without author information).

**Comment by ssm** [comment]
Alexander Koch <notifications@github.com> writes:

> Sure, I'd like to go with the MIT license (although I don't care much,
> so if you've got a better suggestion I'm open to it). Shall I paste
> the entire license in the script or just state the name of the
> license?

For most plugins in the "munin" repo, we just state the name of the
license in the plugin.  (MIT/Expat, MIT/X11, GPL-v12345, Apache-2.0,
etc…)

Some plugins have the entire license text.  I'm fine with both
alternatives.

> I'm a bit irritated

Sorry about that. :/

> because I've seen many plugins without any license information
> (partially even without author information).

Yes, there are many of those, unfortunately.  Tracking down previous
authors, in case that becomes necessary, will take a lot of time.  The
alternative may be to drop them altogether.

-- 
Stig Sandbeck Mathisen

**Comment by lynix** [comment]
Thanks for the info :)  I've added the license commit.

**Pull request merged**
