### PR TITLE
Change folder and category of Bitcoin plugins

### PR DESCRIPTION
**Pull request by Cyclenerd**
To unify the currency plugins I have moved the Bitcoin plugin into the folder `currency` and changed the category to `other`. More I did not make, since I can not test the plugins.

### CODE REVIEW

**Comment by sumpfralle** [comment]
Good!

btw: what is the meaning of "htc"?

**Comment by dipohl** [comment]
On Sun, 02 Jul 2017 04:46:24 -0700
sumpfralle wrote:

> btw: what is the meaning of "htc"?

https://en.wikipedia.org/wiki/High-throughput_computing

http://guide.munin-monitoring.org/en/latest/reference/graph-category.html#well-known-categories

fyi &cheers,

Gabriele

**Comment by sumpfralle** [comment]
@dipohl: thank you!

What a pity - I was still referring people to the old list of well known plugin categories :(

@Cyclenerd: would you please revert your `htc -> other` changes? Sorry!

**Comment by sumpfralle** [comment]
re-fixed in a48cf873338cc13d9a9239fef5d9a1326a98c9a3

**Comment by dipohl** [comment]
On Sun, 02 Jul 2017 17:23:58 +0000 (UTC)
sumpfralle wrote:

> @dipohl: thank you!
> 
> What a pity - I was still referring people to the old list of well known plugin categories :(

this should not really be a problem,
as the old page has a warning box on top saying 
that the content has been been moved to "The Guide"
and has a link included to the new location..

http://gallery.munin-monitoring.org/contrib/htc-index.html

But of course it will be better to point
them to the new location directly ;)

> @Cyclenerd: would you please revert your `htc -> other` changes? Sorry!

I am not sure..
May be the category "other" will be better
as the term HTC is not very common and
only few people will know it..

These are the plugins in that category at the time
http://munin-gallery.dipohl.de/contrib/htc-index.html

fyi & cheers!

Gabriele

**Comment by Cyclenerd** [comment]
+1 for other. I did not know the term `htc` either.

**Comment by dipohl** [comment]
It should [1] not be a problem if you google for term "bitcoin" in the Plugin Gallery:
https://www.google.de/?q=site:http://gallery.munin-monitoring.org+bitcoin

[1] but unfortunately the search is not as efficient as it should be at the time due to many outdated gallery pages on the Munin project server :-(  
I just wrote to steve and the mailing list addressing this issue. Let's hope that it will get solved in the near future..

**Comment by sumpfralle** [comment]
Hehe - so the "htc" term got injected by the author of the bitcoin plugin and was spreading accidentally into the ethereum plugins? Nice :)

I switched the plugins back to `other` ...
(d6dcc5d379edc122547246f6c866658ec9e4d04d)

**Pull request merged**
