### PR TITLE
Fix for pymongo > 3.0 and connection support of MongoClient only

### PR DESCRIPTION
**Pull request by nichok**
https://api.mongodb.com/python/current/changelog.html#mongoclient-changes

### CODE REVIEW

**Comment by benpro** [comment]
Nice. But should use mongodb:// URI to uses authentication.

**Comment by nichok** [comment]
if you need to do auth with a mongodb URI just config settings_host as:

settings_host = 'mongodb://username:password@host/database

(should work... and keep settings_user empty if you do not want to do db.authenticate)

**Comment by benpro** [comment]
This will not work.
```
conn = pymongo.MongoClient(host,port)
```
The ```,port``` part will not handle it.

**Comment by nichok** [comment]
Well, I changed the settings, though if you repeated the same port in both settings it would work (not nice).

Try it now :smile:

**Comment by sumpfralle** [comment]
@nichok / @benpro: this request is ready for merge, right?

**Comment by nichok** [comment]
yes!

**Comment by sumpfralle** [comment]
@benpro did not object, thus I consider all remaining problems to be solved.
Thank you!

**Pull request merged**
