### PR TITLE
Snmp  fixes

### PR DESCRIPTION
**Pull request by shtrom**
Small fixes in a couple of SNMP plugins:
* unify titles and category in snmp__df_ram
* add support for multiple instances of snmp__df_combined

### CODE REVIEW

**Comment by sumpfralle** [comment]
Thank you! This proposal for expanding the usage pattern for the plugin looks good to me.

Personally I would probably prefer something like `graph_name` instead of `script_name`. But besides this, I have no further comments or suggestions.

Did you mark it as "draft" on purpose?

**Comment by shtrom** [comment]
> Did you mark it as "draft" on purpose?

Yes, I want to test it a bit more, but didn't want to forget about the PR (:

**Comment by sumpfralle** [comment]
> Yes, I want to test it a bit more, but didn't want to forget about the PR

Ah - good. Just ping me, when you are ready.

Thanks!

**Comment by shtrom** [comment]
@sumpfralle I think this is good for review. This has been running locally for me for the last two months without major hiccups. The `stackedMax` approach is not great and not foolproof, but that the best we can do (that I can think of).

**Comment by sumpfralle** [comment]
Great, thank you!

**Pull request merged**
