### PR TITLE
[http_load_] Document running from cron with MUNIN_PLUGSTATE

### PR DESCRIPTION
**Pull request by shtrom**
When running from cron, nothing sets MUNIN_PLUGSTATE as needed, so it
needs to be done manually, otherwise the plugin cannot find its cache,
and no data is output.

Signed-off-by: Olivier Mehani <shtrom@ssji.net>

### CODE REVIEW

**Comment by shtrom** [comment]
Hum, CPAN error for a shell plugin. I don't thing the Travis error is linked.

**Comment by steveschnepp** [comment]
A better way would be to leverage the `munin-run` tool that will happily set every variable needed for the plugin.

**Comment by shtrom** [comment]
Ah, right. In my quick test, `munin-run` didn't work, but I must have been doing something wrong. It works nicely, with the oddity that you need to point it to any one of your `http_load_` plugins, and it will update everything.

While I'm at it, here are some other fixes.

**Comment by shtrom** [comment]
Deprecated in favour of #848

**Pull request closed without merging**
