### PR TITLE
[internode_usage] New plugin for Australian ISP Internode

### PR DESCRIPTION
**Pull request by shtrom**
Signed-off-by: Olivier Mehani <shtrom@ssji.net>

### CODE REVIEW

**Comment by shtrom** [comment]
Don't merge just yet: I'm testing that the data I get out is presented with the right granularity.

**Comment by sumpfralle** [comment]
Thank you for working on this.

Just for the technical detail: feel free to squash the fixup commits into their parents (e.g. `git rebase -i --autosquash`) and force-push your branch.

**Comment by shtrom** [comment]
Yup, I'm still working on it and testing locally. I thin I have fixes for a few of the bugs I found.

**Comment by shtrom** [comment]
Some screenshots:
internode_current-day
internode_daily-week
internode_usage-month

**Comment by sumpfralle** [comment]
Just a sidenote: 92db831bc3abed6b7bad5a30e62437371e733fd7 seems to belong to a separate pull request. Additionally I would appreciate a more descriptive comment (e.g. `the single quotes around the here-doc delimiter disable variable substitution (e.g. for '${graph_period}')`). I had to struggle a bit until I understood the context ...

**Comment by shtrom** [comment]
Ah, yeah, I bundled it because it was a quick fix. It was on purpose.

**Comment by sumpfralle** [comment]
> Ah, yeah, I bundled it because it was a quick fix. It was on purpose.

OK - a nifty plan! :)
(agreed)

**Comment by sumpfralle** [comment]
To avoid any misunderstanding: do you think it is ready for merge?
(your last comment from May indicated, that you are still working on it)

**Comment by shtrom** [comment]
Ah, yeah, this one's good to go, it's been chugging along for a few month for me 👍

**Comment by sumpfralle** [comment]
Great!

**Pull request merged**
