### PR TITLE
proc_mem_by_user:

### PR DESCRIPTION
**Pull request by drzraf**
- use of bash
- don't corrupt rrd files when "root" (or any unclean value) is requested

### CODE REVIEW

**Comment by drzraf** [comment]
ping

**Comment by drzraf** [comment]
ping

**Comment by drzraf** [comment]
ping

**Comment by sumpfralle** [comment]
Hi drzraf,

thank you for fixing the "root" issue!

Regarding your proposed change from "sh" to "bash":
The munin plugins are targeting a wide range of platforms including systems that do not contain bash by default (e.g. openwrt, OpenBSD, AIX). Since your change does not require specific bash features, the loss of support for different shell variants does not seem to be compensated by any significant benefit.
Thus please revert this part of your change.

Thank you!
Lars

**Comment by drzraf** [comment]
posix SHell does not support:
* here document
* numeric tests expression ``(( ))``
* multiple fd redirection ``&>``

**Comment by sumpfralle** [comment]
Yes, indeed [ticket #921](http://munin-monitoring.org/ticket/921) should really be fixed.

Regarding sh/bash: sorry for the confusion, I was referring the generation of sh-like interpreters that is similar to the set of features offered by dash. This should work well with all `/bin/sh` interpreters provided by modern operating systems.
`shellcheck -s dash foo` should help you with syntax checks.

**Comment by drzraf** [comment]
Rerolled to comply with "dash-feature-level".
I realized that (at least in recent release), /usr/share/munin/plugins/plugin.sh 's ``clean_fieldname`` provides the root => __root substitution.
About [root issue #921](http://munin-monitoring.org/ticket/921]):
* does anyone still care about Trac?
* is the bug fixed in 3.0?

**Comment by sumpfralle** [comment]
Regarding the `clean_fieldname` munging of "root": good to know!
Trac: I assume it was superseded by github's ticket system.
Thank you for improving the plugin!

**Pull request merged**
