### PR TITLE
Add "process links" graph to ejabberd_resources

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by dotdoom** [comment]
Ping

**Comment by dotdoom** [comment]
Ping

**Comment by dotdoom** [comment]
Ping

**Comment by dotdoom** [comment]
Ping

**Comment by dotdoom** [comment]
Ping

**Comment by dotdoom** [comment]
Ping

**Comment by dotdoom** [comment]
Ping

**Comment by sumpfralle** [comment]
Thank you!
Sorry for the long delay ...

**Pull request merged**
