### PR TITLE
Added munin_events plugin

### PR DESCRIPTION
**Pull request by szepeviktor**
munin_events - Plugin to monitor munin update log

### CODE REVIEW

**Comment by sumpfralle** [comment]
This new plugin looks great!

Do you think, you could switch from "bash" to "sh"? I think, you do no use any bash-specific features.

Otherwise I would merge it as it is.

**Comment by szepeviktor** [comment]
shellcheck tells me:
```
In munin_events line 70:
    local FIELD="$1"
    ^-- SC2039: In POSIX sh, 'local' is undefined.


In munin_events line 71:
    local EVENT_LABEL="$2"
    ^-- SC2039: In POSIX sh, 'local' is undefined.


In munin_events line 72:
    local EVENT_COUNT
    ^-- SC2039: In POSIX sh, 'local' is undefined.


In munin_events line 75:
    if ! [ -z "${EVENT_COUNT//[0-9]/}" ]; then
               ^-- SC2039: In POSIX sh, string replacement is undefined.


In munin_events line 90:
    "$logtail_bin" "$muninupdate" &> /dev/null
                                  ^-- SC2039: In POSIX sh, &> is undefined.
```

I've never met non-Bash shells.

**Comment by szepeviktor** [comment]
We could skid local-s, but what to do with `${EVENT_COUNT//[0-9]/}`?

**Comment by szepeviktor** [comment]
It is quiet sad to live without Bash...

**Comment by sumpfralle** [comment]
uh - sorry: I did phrase exactly, what I wanted.
Indeed I meant "dash", when I said "sh" - sorry for that.
In your case everything was fine before, I think - just the shebang referred to bash instead of sh.
I am sorry to have wasted your time.

Regarding non-bash shells:
* debian's default (non-interactive) shell was changed from bash to dash some years ago
* embedded environments (e.g. openwrt) run with busybox, which contains ash (quite close to dash) - you do not have enough space on most routers to install bash ...

**Comment by szepeviktor** [comment]
OK-OK
Now it is POSIX compatible.

There is a test failure during `cpanm --notest File::Tail::Multi`

Please merge it.

**Comment by szepeviktor** [comment]
Hello!
I do not know what to do.

Using /bin/sh requires me to be POSIX compatible.
Using /bin/bash may not start  on embedded environments.

Please advise.

**Comment by sumpfralle** [comment]
Hello Viktor,

please use "shellcheck -s dash" for your tests. I guess that your original patch just works.

Lars

**Comment by szepeviktor** [comment]
Should I revert to that with /bin/sh ?
FYI That is POSIX, and my scrpit breaks that.

Would you like me to do that?
Please specify exactly what to do.

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by sumpfralle** [comment]
AFAIK /bin/sh points to shell implementations derived from the bourne shell (ash, dash, bash, busybox's sh). Thus the "dash" suite for shellcheck should represent the lowest common denominator of this range of implementations quite well.

Thus please do the following:
* go back to 82edf596896ddcec0e0d75af87790614cfa1f5d0
* replace /bin/bash with /bin/sh
* remove the string replacement in line 75 - probably `echo "$EVENT_COUNT" | grep -q "[^0-9]"` is a suitable alternative
* replace &> in line 90

**Comment by szepeviktor** [comment]
shellcheck is happy about it!

**Comment by sumpfralle** [comment]
It looks good - thank you!
We are discussing the broken test setup on the mailinglist ...

**Pull request merged**
