### PR TITLE
modify comment

### PR DESCRIPTION
**Pull request by bassbone**
/ur/ -> /usr/

### CODE REVIEW

**Comment by ssm** [comment]
I'm not sure about the change to "top", since it is often spectacularly non-portable between systems and versions, while "ps" is easier.

**Comment by bassbone** [comment]
I think "ps" is not the instantaneous CPU utilization, so I want to change to "top".

**Comment by ssm** [comment]
They give the same data, except that "top" emits the "args" field, where the ps output specifies "comm".

Compare:

    diff -u \
      <(top -b -n 1 | awk '{print $9, $12}'|sort) \
      <(ps axo 'pcpu,args' | awk '{print $1, $2}'|sort)

Given that "ps" is more portable across operating system, I prefer that.

**Comment by bassbone** [comment]
FYI
http://www.linuxquestions.org/questions/linux-server-73/top-and-ps-940393/

**Pull request closed without merging**
