### PR TITLE
[docker_] Fake functools.cached_property for Python<3.8

### PR DESCRIPTION
**Pull request by shtrom**
Fixes: #1116
Signed-off-by: Olivier Mehani <shtrom@ssji.net>

### CODE REVIEW

**Comment by shtrom** [comment]
@rwky would you mind testing this out?

**Comment by rwky** [comment]
That seems to sort it :+1:

**Comment by shtrom** [comment]
@rwky I added a small style fixup, shouldn't change the fixed behaviour.

**Comment by rwky** [comment]
Yep still works!

**Comment by shtrom** [comment]
On 4 September 2020 8:14:43 pm AEST, Rowan <notifications@github.com> wrote:
>Yep still works!

Cool, thanks for testing!

I think this is good to squash and merge.
-- 
Olivier Mehani <shtrom@ssji.net>
Sent from my mobile. Please excuse my brevity.

**Comment by sumpfralle** [comment]
This looks good, thank you!

Would you mind to mention in the `except` clause, that it is missing for python before 3.8? This will make it easier to remove this fallback in a few years ...

**Comment by shtrom** [comment]
@sumpfralle done and squashed :+1:

**Comment by sumpfralle** [comment]
Cool - thanks!

**Pull request merged**
