### PR TITLE
add naxsi exceptions plugin

### PR DESCRIPTION
**Pull request by patroqueeet**
plugin to monitor naxsi WAF

### CODE REVIEW

**Review by kenyon — CHANGES_REQUESTED** [review]
Let's put this in a better directory name, like `naxsi` or `waf`.

**Comment by patroqueeet** [comment]
@kenyon done and also made warning/critical levels configurable

**Review by kenyon — APPROVED** [review]

**Comment by patroqueeet** [comment]
@kenyon thx for merging. when will the live site plugin gallery be updated, so we can link it in the naxsi waf docs?

**Comment by kenyon** [comment]
@patroqueeet not sure about that. Will see if I can find out. For now, linking to this github repository should be fine.

**Pull request merged**
