### PR TITLE
Add multigraph plugin for http response codes and times

### PR DESCRIPTION
**Pull request by klaus-tux**
In contrast to using http_responsecode and http_loadtime with the same
configuration, this plugin performs only one request per site and munin
run to gather its statistics.

### CODE REVIEW

**Review by gnuheidix — APPROVED** [review]
It works great and looks well crafted! :-) I already got rid of the other http_* plugins in my setups.

**Comment by sumpfralle** [comment]
Indeed, the plugin looks fine - thank you for your contribution!

**Comment by klaus-tux** [comment]
> Indeed, the plugin looks fine - thank you for your contribution!

Thank you for merging. I'm pleased that you like it :-)

**Comment by sumpfralle** [comment]
In fact it is one of the very few *new* plugins, being just fine as-is-it-is without the need for (even nitpicking-level) improvements.
Congratulations! :)

**Comment by klaus-tux** [comment]
Thank you :-) I fully understand what you mean. I see it as a result of "standing on the shoulders of giants" in combination with applied software craftsmanship.

**Pull request merged**
