### PR TITLE
improvements to some PHP/Apache plugins

### PR DESCRIPTION
**Pull request by drzraf**
* New plugin: apache_cache_disk_count
* apache_average_time_last_n_requests: ability to create multiple instances for distincts log files
* added slow requests for php fpm

### CODE REVIEW

**Comment by leeclemens** [comment]
I believe changing the graph_category deserves mention, was that intentional?

**Comment by drzraf** [comment]
It was although I didn't explored side-effect. I already have php / php-fpm plugins storing results below "php".
I thought that php-fpm is too much specific when visualizing graphs.
But if php-fpm was commonly accepted name as a complete autonomous category, I can change that hunk.

**Comment by leeclemens** [comment]
Since this is only graphing php-fpm's status and the category was already php-fpm, I think it's appropriately specific. If there is a case for changing the category, it at least deserves mention (probably a commit, but at least a comment) that you did so. imo, the category should not be changed without a reason to do so.

**Comment by drzraf** [comment]
granted: remove the change about graph category of php-fpm-process

**Comment by drzraf** [comment]
ping

**Comment by leeclemens** [comment]
IMHO, it doesn't make sense to graph 'slow requests' on the same axis as 'processes'. Besides them being unrelated, slow requests would probably be better as a DERIVE type, while processes should remain a GAUGE type.

**Comment by ssm** [comment]
Please use one pull request per logical change, or per new plugin, that makes it much easier to renew.

**Comment by drzraf** [comment]
PR #707 #708 #709
For php_fpm_process it'll come too including leeclemens's point about multigraph.

**Pull request closed without merging**
