### PR TITLE
certificate_file_expiry: optional logarithmic view for long lived certs

### PR DESCRIPTION
**Pull request by ap-wtioit**
logarithmic was removed in d885a314ade7c1287237d61f4d2b1f24db509533
but still has it's benefits for openvpn CA and CRL certs. when enabling
logarithmic we keep the SI units now instead of rrdtools default
scientific notation.

This enables using logarithmic graph as an option again that was removed in #1266.

Info @wt-io-it

### CODE REVIEW

**Comment by sumpfralle** [comment]
Thanks for taking a look at this!

Maybe it would be sufficient to enforce the SI notation and keep the logarithmic visualization enabled by default (as it was before)?

@kimheino / @ap-wtioit: what do you think?

**Comment by ap-wtioit** [comment]
i would think `LOGARITHMIC=yes` as default that would keep the old behavior and still give the user the option to disable the logarithmic graph view so be the best option.

**Comment by kimheino** [comment]
"yes" as default works for me. I'll probably change it to "no" in my config.

**Comment by sumpfralle** [comment]
That was quick - thanks!

**Pull request merged**
