### PR TITLE
[plugins/transmission] Python3 compat

### PR DESCRIPTION
**Pull request by shtrom**
Signed-off-by: Olivier Mehani <shtrom@ssji.net>

### CODE REVIEW

**Comment by sumpfralle** [comment]
That looks good!

How about switching the shebang to `python3`? (Python2 is end-of-life anyway)

**Comment by shtrom** [comment]
Yup. I didn't want to be too destructive for the moment, as the changes are backward compatible, and still work with Python2, too. So I decided to remain on the fence (:

**Comment by sumpfralle** [comment]
Following [PEP-394](https://www.python.org/dev/peps/pep-0394/#for-python-script-publishers) I would like to replace the `python` shebang with either `python2` or `python3` (since we do not expect the plugin to be executed in a virtual environment).

Thus if you hesitate to change the shebang, then I would do it afterwards :)

**Comment by shtrom** [comment]
Ah, I wasn't aware of the PEP. I actually did run into this issue on a Debian machine of mine, where `python` disappeared, and I had to install `python-is-python3`, which then highlighted this issue.

The code as it stands is compatible with both Python 2 and 3, so I'm not sure whether it's great for the users to potentially force a move to a new Python while the rest of their system still hasn't been updated. Arguably, this is only for old systems, but this would force a breaking change in the plugin that is not strictly necessary.

Unless we have a strict requirement in munin or munin-contrib to have Python _3_ installed, I think it would be less disruptive to stick to `python` in the shebang for now.

**Comment by sumpfralle** [comment]
> Arguably, this is only for old systems, but this would force a breaking change in the plugin that is not strictly necessary.

The last actively maintained distribution, that *does not* ship python3 is RHEL5. It will be end-of-life next week.

Thus within 72 hours there will be *no* distribution, that does not contain python3.

From my point of view, everything pushes into the direction of `python3`:
* PEP 394 recommends it
* Debian and derivatives need manual interaction for providing `python`
* every distribution released in the last few years has more likely `python3` installed, than `python`

It is about time to move on :)

**Comment by shtrom** [comment]
On Fri 27 Nov 2020 at 04:08:18 -0800, Lars Kruse wrote:
>It is about time to move on :)

Oh, yeah, that's for sure. My concern is more about breaking old systems 
running in the wild that may not actually get upgraded.

But ok, I'll update the shebang.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by sumpfralle** [comment]
Thanks!

**Pull request merged**
