### PR TITLE
Fix asterisk ami parsing

### PR DESCRIPTION
**Pull request by lelutin**
This patch set should make the asterisk multi-graph plugin work again on recent versions of Asterisk.

### CODE REVIEW

**Comment by lelutin** [comment]
withtout the two additional commits that fix a series of typoes in "config" output, the plugin does not work at all (e.g. munin-update can't complete polling for that plugin)

**Comment by sumpfralle** [comment]
Hehe - what a nice cleanup - thank you!

**Comment by lelutin** [comment]
oops! I just spotted an issue with my PR: I left two lines of debugging that won't work. I'll submit the fix now to output those only if MUNIN_DEBUG is set.

**Comment by lelutin** [comment]
ok, I've submitted #1006 for the fix

**Comment by sumpfralle** [comment]
No problem - thank you for fixing up the issue!

**Pull request merged**
